### ISSUE TITLE
How to convert this time velue to actual time?

### ISSUE THREAD

**Issue by rohanarihant** [yury-dymov/react-bootstrap-time-picker#1]
Hi,
Thanx for this react-bootstrap-time-picker.Whenever I am saving time, I got time value in integer(57600).How can I convert this integer value to actual time format 04:00PM.

**Comment by yury-dymov** [comment]
You can use [time-number](https://github.com/yury-dymov/time-number] for that

**Comment by rohanarihant** [comment]
thank you for quick support and update me for 12 hour format.

**Comment by yury-dymov** [comment]
Done. Please check, and feel free to close if everything works well for you.

**Comment by rohanarihant** [comment]
Its working fine. Thank You

**Comment by rohanarihant** [comment]
hi @yury-dymov Time format in 12 hours is not working.
console.log(timeFromInt(e, { format: 12 }));   //15:20

**Comment by yury-dymov** [comment]
```
test('timeToInt 15:30', () => {
    expect(timeFromInt(15 * 3600 + 30 * 60, { format: 12 })).toBe('03:30 PM');
  });
```
test is green. I suppose I haven't update the dep for `time-picker`. Doing this atm

**Comment by rohanarihant** [comment]
sorry @yury-dymov but It's not working.
console.log(timeFromInt(15 * 3600 + 30 * 60, { format: 12 }));         //15:30

**Comment by yury-dymov** [comment]
May you confirm that you are using `react-bootstrap-time-picker` v.1.0.2 and `time-number` v.1.1.0 and also that your bundle was rebuild after the update?

**Comment by rohanarihant** [comment]
ok fine.
