### ISSUE TITLE
Module not found: Can't resolve 'react-bootstrap/lib/FormControl' in '/node_modules/react-bootstrap-time-picker/dist'

### ISSUE THREAD

**Issue by kruyvanna** [yury-dymov/react-bootstrap-time-picker#3]
Hi,

I try to use this lib but got module not found error

`Module not found: Can't resolve 'react-bootstrap/lib/FormControl' in '/node_modules/react-bootstrap-time-picker/dist'`

**Comment by yury-dymov** [comment]
Please try to add peerDependency `react-bootstrap` (`npm i --save react-bootstrap`). Let me know if it helped

**Comment by kruyvanna** [comment]
@yury-dymov it works now! Thanks

**Comment by Rajeshbhartia** [comment]
How to set the height of the drop-down options.

**Comment by Hsowndarya** [comment]
`Module not found: Can't resolve 'react-bootstrap/lib/FormControl' in '/node_modules/react-bootstrap-time-picker/dist'`

**Comment by darwin2k** [comment]
@Hsowndarya  You have to use an old version of react-bootstrap
"react-bootstrap": "^0.30.3",

**Comment by CollinsLord** [comment]
npm react-bootstrap     will fix this for

**Comment by ridbay** [comment]
This is what I did
import Form from 'react-bootstrap/Form' instead of import FormGroup from 'react-bootstrap/lib/FormGroup',
import ControlLabel from 'react-bootstrap/lib/ControlLabel';,
import FormControl from 'react-bootstrap/lib/FormControl'; 
Then I used Form.Group, Form.Label Form.Control components in place of FormGroup, ControlLabel, FormControl and my form works fine.

**Comment by RobotFights** [comment]
Still not working for me

**Comment by RobotFights** [comment]
![react](https://user-images.githubusercontent.com/45731476/66458829-8dcb1980-ea28-11e9-9594-e4e250a11d57.jpg)

**Comment by CollinsLord** [comment]
Can u send post the error u are getting

**Comment by RobotFights** [comment]
![react](https://user-images.githubusercontent.com/45731476/66461024-f0beaf80-ea2c-11e9-9d5f-f1e5920cc5cc.jpg)

**Comment by RobotFights** [comment]
@CollinsLord Here's the error: 

./src/App.js
Module not found: Can't resolve 'react-bootstrap/lib/ControlLabel' in 'C:\Users\robot55\Desktop\markdown-previewer\src'

**Comment by mehul100100** [comment]
I am having the same issue. Can anybody fix this for me?
![image](https://user-images.githubusercontent.com/86203568/122740085-41c61400-d2a1-11eb-97c4-eb33f3a5dc88.png)

**Comment by YasirHasn9** [comment]
Usually this happened when the version react-bootstrap changes, to fix them, I recommend to always go back to the old version

**Comment by krushangSk17** [comment]
use react-bootstrap version 👍 
> ^0.30.3

using this i have resolved the same problem.

**Comment by ViableSystemModel** [comment]
I had my auto-complete in VS Code autofill `import { Component Name} from 'react-bootstrap/lib/ComponentName'` when `import ComponentName from 'react-bootstrap/ComponentName'` would have been appropriate. Maybe this is more of an issue with intellisense
