### ISSUE TITLE
Can't resolve 'react-bootstrap/lib/FormControl'

### ISSUE THREAD

**Issue by Wishmaker888** [yury-dymov/react-bootstrap-time-picker#5]
Seems like it doesn't work with React v16.3.2

**Comment by yury-dymov** [comment]
You need to install peer dependency ‘react-bootstrap’

**Comment by Wishmaker888** [comment]
Yeah, that works. Thanks!

**Comment by alyssa1995** [comment]
this is not working again with the react-bootstrap dependency

**Comment by yury-dymov** [comment]
@alyssa1995 I'll update the package once `react-bootstrap` 1.0.0 is released. I am not supporting alpha and beta
