### ISSUE TITLE
ReferenceError: require is not defined

### ISSUE THREAD

**Issue by sandhysanjaya1206** [yury-dymov/react-bootstrap-time-picker#7]
ReferenceError: require is not defined

`ReferenceError: require is not defined
eval
webpack-internal:///3:1:18
push../node_modules/react-bootstrap-time-picker/dist/bundle.js
node_modules/react-bootstrap-time-picker/dist/bundle.js:40`

**Comment by alecgonzales** [comment]
I'm getting the same error

**Comment by yury-dymov** [comment]
Resolved, thank you for report
